import type { Metadata } from "next";
import { Inter } from "next/font/google";
import  theme  from "@/app/lib/thems";
import { ThemeProvider, Container } from "@mui/material";
import NavBar from "@/app/component/header/Navbar";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
        <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
                <NavBar></NavBar>
                <Container>
                    {children}
                </Container>
            </ThemeProvider>
        </AppRouterCacheProvider>
    </body>
    </html>
  );
}
