import type { Metadata } from "next";
import { Inter } from "next/font/google";
import  { theme } from "@/app/lib/thems";
import { ThemeProvider, Container } from "@mui/material";
import NavBar from "@/app/component/header/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/>
        <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Roboto:wght@100,200,300;400;500;700&display=swap"
        />
        <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
    </head>
    <body>
        <ThemeProvider theme={theme}>
            <NavBar></NavBar>
            <Container>
                {children}
            </Container>
        </ThemeProvider>
    </body>
    </html>
  );
}
